import '@/app/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });
import { ChatNotification } from '@/components/meditation/ChatNotification';
import { AuthProvider } from '@/provider/AuthProvider';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
          {children}
          <ChatNotification />
        </AuthProvider>
      </body>
    </html>
  );
}
