import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@/app/globals.css';
import Header from '@/components/header'
// import { AuthProvider } from '@/components/providers/AuthProvider';
// import { Toaster } from '@/components/ui/sonner';
import { MessengerButton } from '@/components/chat/MessengerButton';
import { ChatNotifications } from '@/components/notifications/ChatNotifications';
import { ReverendNotifications } from '@/components/notifications/ReverendNotifications';
import { AuthProvider } from '@/provider/AuthProvider';
import { Toaster } from "@/components/ui/toaster"
import { UserNotificationProvider } from "@/components/providers/UserNotificationProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* {children}
        <Toaster position="top-right" reverseOrder={false} /> */}
        <AuthProvider>
        <UserNotificationProvider>
        <Header/>
          {children}
          {/* <MessengerButton /> */}
          {/* <ChatNotifications /> */}
          <ReverendNotifications />
          <Toaster/>
          </UserNotificationProvider>
        </AuthProvider>
        </body>
    </html>
  );
}
