import '@/app/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import { MessengerButton } from '@/components/chat/MessengerButton';
import { ChatNotifications } from '@/components/notifications/ChatNotifications';
import { ReverendNotifications } from '@/components/notifications/ReverendNotifications';
import { AuthProvider } from '@/provider/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
          {children}
          <MessengerButton />
          <ChatNotifications />
          <ReverendNotifications />
          <Toaster position="bottom-right" />
        </AuthProvider>
        </body>

    </html>
  );
}
